version: "3"
services:
    db:
        image: postgres:9.6
        environment:
            POSTGRES_USER: api-service
            POSTGRES_PASSWORD: api-service
            POSTGRES_DB: api-service
        ports:
            - 5432:5432

    api-service:
        build: .
        environment:
            APP_NAME: Laravel
            APP_ENV: local
            APP_KEY:
            APP_DEBUG: "true"
            APP_URL: http://localhost

            LOG_CHANNEL: stack
            LOG_DEPRECATIONS_CHANNEL: null
            LOG_LEVEL: debug

            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: api-service
            DB_USERNAME: api-service
            DB_PASSWORD: api-service

            BROADCAST_DRIVER: log
            CACHE_DRIVER: file
            FILESYSTEM_DISK: local
            QUEUE_CONNECTION: sync
            SESSION_DRIVER: file
            SESSION_LIFETIME: 120

            MAIL_MAILER: smtp
            MAIL_HOST: mailpit
            MAIL_PORT: 1025
            MAIL_USERNAME: null
            MAIL_PASSWORD: null
            MAIL_ENCRYPTION: null
            MAIL_FROM_ADDRESS: "hello@example.com"
            MAIL_FROM_NAME: "${APP_NAME}"

            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:
            AWS_DEFAULT_REGION: us-east-1
            AWS_BUCKET:
            AWS_USE_PATH_STYLE_ENDPOINT: "false"

            PUSHER_APP_ID:
            PUSHER_APP_KEY:
            PUSHER_APP_SECRET:
            PUSHER_HOST:
            PUSHER_PORT: 443
            PUSHER_SCHEME: https
            PUSHER_APP_CLUSTER: mt1

            VITE_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
            VITE_PUSHER_HOST: "${PUSHER_HOST}"
            VITE_PUSHER_PORT: "${PUSHER_PORT}"
            VITE_PUSHER_SCHEME: "${PUSHER_SCHEME}"
            VITE_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"
        
        volumes:
            - .:/var/www/html

        ports:
            - 8000:8000
        depends_on:
            - db